/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTenantSlugRouteImport } from './routes/t.$tenantSlug'
import { Route as TTenantSlugIndexRouteImport } from './routes/t.$tenantSlug.index'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantSlugRoute = TTenantSlugRouteImport.update({
  id: '/t/$tenantSlug',
  path: '/t/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantSlugIndexRoute = TTenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacao': typeof AutomacaoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/leads': typeof LeadsRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/relatorios': typeof RelatoriosRoute
  '/super-admin': typeof SuperAdminRoute
  '/tarefas': typeof TarefasRoute
  '/t/$tenantSlug': typeof TTenantSlugRouteWithChildren
  '/t/$tenantSlug/': typeof TTenantSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacao': typeof AutomacaoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/leads': typeof LeadsRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/relatorios': typeof RelatoriosRoute
  '/super-admin': typeof SuperAdminRoute
  '/tarefas': typeof TarefasRoute
  '/t/$tenantSlug': typeof TTenantSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacao': typeof AutomacaoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/leads': typeof LeadsRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/relatorios': typeof RelatoriosRoute
  '/super-admin': typeof SuperAdminRoute
  '/tarefas': typeof TarefasRoute
  '/t/$tenantSlug': typeof TTenantSlugRouteWithChildren
  '/t/$tenantSlug/': typeof TTenantSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automacao'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/insights'
    | '/leads'
    | '/onboarding'
    | '/pipeline'
    | '/relatorios'
    | '/super-admin'
    | '/tarefas'
    | '/t/$tenantSlug'
    | '/t/$tenantSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automacao'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/insights'
    | '/leads'
    | '/onboarding'
    | '/pipeline'
    | '/relatorios'
    | '/super-admin'
    | '/tarefas'
    | '/t/$tenantSlug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/automacao'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/insights'
    | '/leads'
    | '/onboarding'
    | '/pipeline'
    | '/relatorios'
    | '/super-admin'
    | '/tarefas'
    | '/t/$tenantSlug'
    | '/t/$tenantSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AutomacaoRoute: typeof AutomacaoRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InsightsRoute: typeof InsightsRoute
  LeadsRoute: typeof LeadsRoute
  OnboardingRoute: typeof OnboardingRoute
  PipelineRoute: typeof PipelineRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TarefasRoute: typeof TarefasRoute
  TTenantSlugRoute: typeof TTenantSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenantSlug': {
      id: '/t/$tenantSlug'
      path: '/t/$tenantSlug'
      fullPath: '/t/$tenantSlug'
      preLoaderRoute: typeof TTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenantSlug/': {
      id: '/t/$tenantSlug/'
      path: '/'
      fullPath: '/t/$tenantSlug/'
      preLoaderRoute: typeof TTenantSlugIndexRouteImport
      parentRoute: typeof TTenantSlugRoute
    }
  }
}

interface TTenantSlugRouteChildren {
  TTenantSlugIndexRoute: typeof TTenantSlugIndexRoute
}

const TTenantSlugRouteChildren: TTenantSlugRouteChildren = {
  TTenantSlugIndexRoute: TTenantSlugIndexRoute,
}

const TTenantSlugRouteWithChildren = TTenantSlugRoute._addFileChildren(
  TTenantSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AutomacaoRoute: AutomacaoRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FinanceiroRoute: FinanceiroRoute,
  InsightsRoute: InsightsRoute,
  LeadsRoute: LeadsRoute,
  OnboardingRoute: OnboardingRoute,
  PipelineRoute: PipelineRoute,
  RelatoriosRoute: RelatoriosRoute,
  SuperAdminRoute: SuperAdminRoute,
  TarefasRoute: TarefasRoute,
  TTenantSlugRoute: TTenantSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
