/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LandingPagesRouteImport } from './routes/landing-pages'
import { Route as InteracoesRouteImport } from './routes/interacoes'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EscolarRouteImport } from './routes/escolar'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as EmailMarketingRouteImport } from './routes/email-marketing'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClinicasRouteImport } from './routes/clinicas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as BaseConhecimentoRouteImport } from './routes/base-conhecimento'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscolarIndexRouteImport } from './routes/escolar.index'
import { Route as ClinicasIndexRouteImport } from './routes/clinicas.index'
import { Route as TTenantSlugRouteImport } from './routes/t.$tenantSlug'
import { Route as EscolarTurmasRouteImport } from './routes/escolar.turmas'
import { Route as EscolarProfessoresRouteImport } from './routes/escolar.professores'
import { Route as EscolarCursosRouteImport } from './routes/escolar.cursos'
import { Route as EscolarAlunosRouteImport } from './routes/escolar.alunos'
import { Route as ClinicasProntuariosRouteImport } from './routes/clinicas.prontuarios'
import { Route as ClinicasPacientesRouteImport } from './routes/clinicas.pacientes'
import { Route as ClinicasConfiguracoesRouteImport } from './routes/clinicas.configuracoes'
import { Route as ClinicasAgendaRouteImport } from './routes/clinicas.agenda'
import { Route as TTenantSlugIndexRouteImport } from './routes/t.$tenantSlug.index'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPagesRoute = LandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const InteracoesRoute = InteracoesRouteImport.update({
  id: '/interacoes',
  path: '/interacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolarRoute = EscolarRouteImport.update({
  id: '/escolar',
  path: '/escolar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailMarketingRoute = EmailMarketingRouteImport.update({
  id: '/email-marketing',
  path: '/email-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicasRoute = ClinicasRouteImport.update({
  id: '/clinicas',
  path: '/clinicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseConhecimentoRoute = BaseConhecimentoRouteImport.update({
  id: '/base-conhecimento',
  path: '/base-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolarIndexRoute = EscolarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EscolarRoute,
} as any)
const ClinicasIndexRoute = ClinicasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicasRoute,
} as any)
const TTenantSlugRoute = TTenantSlugRouteImport.update({
  id: '/t/$tenantSlug',
  path: '/t/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolarTurmasRoute = EscolarTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => EscolarRoute,
} as any)
const EscolarProfessoresRoute = EscolarProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => EscolarRoute,
} as any)
const EscolarCursosRoute = EscolarCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => EscolarRoute,
} as any)
const EscolarAlunosRoute = EscolarAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => EscolarRoute,
} as any)
const ClinicasProntuariosRoute = ClinicasProntuariosRouteImport.update({
  id: '/prontuarios',
  path: '/prontuarios',
  getParentRoute: () => ClinicasRoute,
} as any)
const ClinicasPacientesRoute = ClinicasPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => ClinicasRoute,
} as any)
const ClinicasConfiguracoesRoute = ClinicasConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ClinicasRoute,
} as any)
const ClinicasAgendaRoute = ClinicasAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ClinicasRoute,
} as any)
const TTenantSlugIndexRoute = TTenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacao': typeof AutomacaoRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/campanhas': typeof CampanhasRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/clinicas': typeof ClinicasRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/dashboards': typeof DashboardsRoute
  '/email-marketing': typeof EmailMarketingRoute
  '/empresas': typeof EmpresasRoute
  '/escolar': typeof EscolarRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/interacoes': typeof InteracoesRoute
  '/landing-pages': typeof LandingPagesRoute
  '/leads': typeof LeadsRoute
  '/onboarding': typeof OnboardingRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pipeline': typeof PipelineRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/super-admin': typeof SuperAdminRoute
  '/tarefas': typeof TarefasRoute
  '/tickets': typeof TicketsRoute
  '/clinicas/agenda': typeof ClinicasAgendaRoute
  '/clinicas/configuracoes': typeof ClinicasConfiguracoesRoute
  '/clinicas/pacientes': typeof ClinicasPacientesRoute
  '/clinicas/prontuarios': typeof ClinicasProntuariosRoute
  '/escolar/alunos': typeof EscolarAlunosRoute
  '/escolar/cursos': typeof EscolarCursosRoute
  '/escolar/professores': typeof EscolarProfessoresRoute
  '/escolar/turmas': typeof EscolarTurmasRoute
  '/t/$tenantSlug': typeof TTenantSlugRouteWithChildren
  '/clinicas/': typeof ClinicasIndexRoute
  '/escolar/': typeof EscolarIndexRoute
  '/t/$tenantSlug/': typeof TTenantSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacao': typeof AutomacaoRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/campanhas': typeof CampanhasRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/dashboards': typeof DashboardsRoute
  '/email-marketing': typeof EmailMarketingRoute
  '/empresas': typeof EmpresasRoute
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/interacoes': typeof InteracoesRoute
  '/landing-pages': typeof LandingPagesRoute
  '/leads': typeof LeadsRoute
  '/onboarding': typeof OnboardingRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pipeline': typeof PipelineRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/super-admin': typeof SuperAdminRoute
  '/tarefas': typeof TarefasRoute
  '/tickets': typeof TicketsRoute
  '/clinicas/agenda': typeof ClinicasAgendaRoute
  '/clinicas/configuracoes': typeof ClinicasConfiguracoesRoute
  '/clinicas/pacientes': typeof ClinicasPacientesRoute
  '/clinicas/prontuarios': typeof ClinicasProntuariosRoute
  '/escolar/alunos': typeof EscolarAlunosRoute
  '/escolar/cursos': typeof EscolarCursosRoute
  '/escolar/professores': typeof EscolarProfessoresRoute
  '/escolar/turmas': typeof EscolarTurmasRoute
  '/clinicas': typeof ClinicasIndexRoute
  '/escolar': typeof EscolarIndexRoute
  '/t/$tenantSlug': typeof TTenantSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacao': typeof AutomacaoRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/campanhas': typeof CampanhasRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/clinicas': typeof ClinicasRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/dashboards': typeof DashboardsRoute
  '/email-marketing': typeof EmailMarketingRoute
  '/empresas': typeof EmpresasRoute
  '/escolar': typeof EscolarRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/interacoes': typeof InteracoesRoute
  '/landing-pages': typeof LandingPagesRoute
  '/leads': typeof LeadsRoute
  '/onboarding': typeof OnboardingRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pipeline': typeof PipelineRoute
  '/propostas': typeof PropostasRoute
  '/relatorios': typeof RelatoriosRoute
  '/super-admin': typeof SuperAdminRoute
  '/tarefas': typeof TarefasRoute
  '/tickets': typeof TicketsRoute
  '/clinicas/agenda': typeof ClinicasAgendaRoute
  '/clinicas/configuracoes': typeof ClinicasConfiguracoesRoute
  '/clinicas/pacientes': typeof ClinicasPacientesRoute
  '/clinicas/prontuarios': typeof ClinicasProntuariosRoute
  '/escolar/alunos': typeof EscolarAlunosRoute
  '/escolar/cursos': typeof EscolarCursosRoute
  '/escolar/professores': typeof EscolarProfessoresRoute
  '/escolar/turmas': typeof EscolarTurmasRoute
  '/t/$tenantSlug': typeof TTenantSlugRouteWithChildren
  '/clinicas/': typeof ClinicasIndexRoute
  '/escolar/': typeof EscolarIndexRoute
  '/t/$tenantSlug/': typeof TTenantSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automacao'
    | '/base-conhecimento'
    | '/campanhas'
    | '/chat'
    | '/clientes'
    | '/clinicas'
    | '/configuracoes'
    | '/contatos'
    | '/dashboards'
    | '/email-marketing'
    | '/empresas'
    | '/escolar'
    | '/financeiro'
    | '/insights'
    | '/interacoes'
    | '/landing-pages'
    | '/leads'
    | '/onboarding'
    | '/oportunidades'
    | '/pipeline'
    | '/propostas'
    | '/relatorios'
    | '/super-admin'
    | '/tarefas'
    | '/tickets'
    | '/clinicas/agenda'
    | '/clinicas/configuracoes'
    | '/clinicas/pacientes'
    | '/clinicas/prontuarios'
    | '/escolar/alunos'
    | '/escolar/cursos'
    | '/escolar/professores'
    | '/escolar/turmas'
    | '/t/$tenantSlug'
    | '/clinicas/'
    | '/escolar/'
    | '/t/$tenantSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automacao'
    | '/base-conhecimento'
    | '/campanhas'
    | '/chat'
    | '/clientes'
    | '/configuracoes'
    | '/contatos'
    | '/dashboards'
    | '/email-marketing'
    | '/empresas'
    | '/financeiro'
    | '/insights'
    | '/interacoes'
    | '/landing-pages'
    | '/leads'
    | '/onboarding'
    | '/oportunidades'
    | '/pipeline'
    | '/propostas'
    | '/relatorios'
    | '/super-admin'
    | '/tarefas'
    | '/tickets'
    | '/clinicas/agenda'
    | '/clinicas/configuracoes'
    | '/clinicas/pacientes'
    | '/clinicas/prontuarios'
    | '/escolar/alunos'
    | '/escolar/cursos'
    | '/escolar/professores'
    | '/escolar/turmas'
    | '/clinicas'
    | '/escolar'
    | '/t/$tenantSlug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/automacao'
    | '/base-conhecimento'
    | '/campanhas'
    | '/chat'
    | '/clientes'
    | '/clinicas'
    | '/configuracoes'
    | '/contatos'
    | '/dashboards'
    | '/email-marketing'
    | '/empresas'
    | '/escolar'
    | '/financeiro'
    | '/insights'
    | '/interacoes'
    | '/landing-pages'
    | '/leads'
    | '/onboarding'
    | '/oportunidades'
    | '/pipeline'
    | '/propostas'
    | '/relatorios'
    | '/super-admin'
    | '/tarefas'
    | '/tickets'
    | '/clinicas/agenda'
    | '/clinicas/configuracoes'
    | '/clinicas/pacientes'
    | '/clinicas/prontuarios'
    | '/escolar/alunos'
    | '/escolar/cursos'
    | '/escolar/professores'
    | '/escolar/turmas'
    | '/t/$tenantSlug'
    | '/clinicas/'
    | '/escolar/'
    | '/t/$tenantSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AutomacaoRoute: typeof AutomacaoRoute
  BaseConhecimentoRoute: typeof BaseConhecimentoRoute
  CampanhasRoute: typeof CampanhasRoute
  ChatRoute: typeof ChatRoute
  ClientesRoute: typeof ClientesRoute
  ClinicasRoute: typeof ClinicasRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContatosRoute: typeof ContatosRoute
  DashboardsRoute: typeof DashboardsRoute
  EmailMarketingRoute: typeof EmailMarketingRoute
  EmpresasRoute: typeof EmpresasRoute
  EscolarRoute: typeof EscolarRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRoute
  InsightsRoute: typeof InsightsRoute
  InteracoesRoute: typeof InteracoesRoute
  LandingPagesRoute: typeof LandingPagesRoute
  LeadsRoute: typeof LeadsRoute
  OnboardingRoute: typeof OnboardingRoute
  OportunidadesRoute: typeof OportunidadesRoute
  PipelineRoute: typeof PipelineRoute
  PropostasRoute: typeof PropostasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TarefasRoute: typeof TarefasRoute
  TicketsRoute: typeof TicketsRoute
  TTenantSlugRoute: typeof TTenantSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-pages': {
      id: '/landing-pages'
      path: '/landing-pages'
      fullPath: '/landing-pages'
      preLoaderRoute: typeof LandingPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interacoes': {
      id: '/interacoes'
      path: '/interacoes'
      fullPath: '/interacoes'
      preLoaderRoute: typeof InteracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolar': {
      id: '/escolar'
      path: '/escolar'
      fullPath: '/escolar'
      preLoaderRoute: typeof EscolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-marketing': {
      id: '/email-marketing'
      path: '/email-marketing'
      fullPath: '/email-marketing'
      preLoaderRoute: typeof EmailMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicas': {
      id: '/clinicas'
      path: '/clinicas'
      fullPath: '/clinicas'
      preLoaderRoute: typeof ClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-conhecimento': {
      id: '/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof BaseConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolar/': {
      id: '/escolar/'
      path: '/'
      fullPath: '/escolar/'
      preLoaderRoute: typeof EscolarIndexRouteImport
      parentRoute: typeof EscolarRoute
    }
    '/clinicas/': {
      id: '/clinicas/'
      path: '/'
      fullPath: '/clinicas/'
      preLoaderRoute: typeof ClinicasIndexRouteImport
      parentRoute: typeof ClinicasRoute
    }
    '/t/$tenantSlug': {
      id: '/t/$tenantSlug'
      path: '/t/$tenantSlug'
      fullPath: '/t/$tenantSlug'
      preLoaderRoute: typeof TTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolar/turmas': {
      id: '/escolar/turmas'
      path: '/turmas'
      fullPath: '/escolar/turmas'
      preLoaderRoute: typeof EscolarTurmasRouteImport
      parentRoute: typeof EscolarRoute
    }
    '/escolar/professores': {
      id: '/escolar/professores'
      path: '/professores'
      fullPath: '/escolar/professores'
      preLoaderRoute: typeof EscolarProfessoresRouteImport
      parentRoute: typeof EscolarRoute
    }
    '/escolar/cursos': {
      id: '/escolar/cursos'
      path: '/cursos'
      fullPath: '/escolar/cursos'
      preLoaderRoute: typeof EscolarCursosRouteImport
      parentRoute: typeof EscolarRoute
    }
    '/escolar/alunos': {
      id: '/escolar/alunos'
      path: '/alunos'
      fullPath: '/escolar/alunos'
      preLoaderRoute: typeof EscolarAlunosRouteImport
      parentRoute: typeof EscolarRoute
    }
    '/clinicas/prontuarios': {
      id: '/clinicas/prontuarios'
      path: '/prontuarios'
      fullPath: '/clinicas/prontuarios'
      preLoaderRoute: typeof ClinicasProntuariosRouteImport
      parentRoute: typeof ClinicasRoute
    }
    '/clinicas/pacientes': {
      id: '/clinicas/pacientes'
      path: '/pacientes'
      fullPath: '/clinicas/pacientes'
      preLoaderRoute: typeof ClinicasPacientesRouteImport
      parentRoute: typeof ClinicasRoute
    }
    '/clinicas/configuracoes': {
      id: '/clinicas/configuracoes'
      path: '/configuracoes'
      fullPath: '/clinicas/configuracoes'
      preLoaderRoute: typeof ClinicasConfiguracoesRouteImport
      parentRoute: typeof ClinicasRoute
    }
    '/clinicas/agenda': {
      id: '/clinicas/agenda'
      path: '/agenda'
      fullPath: '/clinicas/agenda'
      preLoaderRoute: typeof ClinicasAgendaRouteImport
      parentRoute: typeof ClinicasRoute
    }
    '/t/$tenantSlug/': {
      id: '/t/$tenantSlug/'
      path: '/'
      fullPath: '/t/$tenantSlug/'
      preLoaderRoute: typeof TTenantSlugIndexRouteImport
      parentRoute: typeof TTenantSlugRoute
    }
  }
}

interface ClinicasRouteChildren {
  ClinicasAgendaRoute: typeof ClinicasAgendaRoute
  ClinicasConfiguracoesRoute: typeof ClinicasConfiguracoesRoute
  ClinicasPacientesRoute: typeof ClinicasPacientesRoute
  ClinicasProntuariosRoute: typeof ClinicasProntuariosRoute
  ClinicasIndexRoute: typeof ClinicasIndexRoute
}

const ClinicasRouteChildren: ClinicasRouteChildren = {
  ClinicasAgendaRoute: ClinicasAgendaRoute,
  ClinicasConfiguracoesRoute: ClinicasConfiguracoesRoute,
  ClinicasPacientesRoute: ClinicasPacientesRoute,
  ClinicasProntuariosRoute: ClinicasProntuariosRoute,
  ClinicasIndexRoute: ClinicasIndexRoute,
}

const ClinicasRouteWithChildren = ClinicasRoute._addFileChildren(
  ClinicasRouteChildren,
)

interface EscolarRouteChildren {
  EscolarAlunosRoute: typeof EscolarAlunosRoute
  EscolarCursosRoute: typeof EscolarCursosRoute
  EscolarProfessoresRoute: typeof EscolarProfessoresRoute
  EscolarTurmasRoute: typeof EscolarTurmasRoute
  EscolarIndexRoute: typeof EscolarIndexRoute
}

const EscolarRouteChildren: EscolarRouteChildren = {
  EscolarAlunosRoute: EscolarAlunosRoute,
  EscolarCursosRoute: EscolarCursosRoute,
  EscolarProfessoresRoute: EscolarProfessoresRoute,
  EscolarTurmasRoute: EscolarTurmasRoute,
  EscolarIndexRoute: EscolarIndexRoute,
}

const EscolarRouteWithChildren =
  EscolarRoute._addFileChildren(EscolarRouteChildren)

interface TTenantSlugRouteChildren {
  TTenantSlugIndexRoute: typeof TTenantSlugIndexRoute
}

const TTenantSlugRouteChildren: TTenantSlugRouteChildren = {
  TTenantSlugIndexRoute: TTenantSlugIndexRoute,
}

const TTenantSlugRouteWithChildren = TTenantSlugRoute._addFileChildren(
  TTenantSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AutomacaoRoute: AutomacaoRoute,
  BaseConhecimentoRoute: BaseConhecimentoRoute,
  CampanhasRoute: CampanhasRoute,
  ChatRoute: ChatRoute,
  ClientesRoute: ClientesRoute,
  ClinicasRoute: ClinicasRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContatosRoute: ContatosRoute,
  DashboardsRoute: DashboardsRoute,
  EmailMarketingRoute: EmailMarketingRoute,
  EmpresasRoute: EmpresasRoute,
  EscolarRoute: EscolarRouteWithChildren,
  FinanceiroRoute: FinanceiroRoute,
  InsightsRoute: InsightsRoute,
  InteracoesRoute: InteracoesRoute,
  LandingPagesRoute: LandingPagesRoute,
  LeadsRoute: LeadsRoute,
  OnboardingRoute: OnboardingRoute,
  OportunidadesRoute: OportunidadesRoute,
  PipelineRoute: PipelineRoute,
  PropostasRoute: PropostasRoute,
  RelatoriosRoute: RelatoriosRoute,
  SuperAdminRoute: SuperAdminRoute,
  TarefasRoute: TarefasRoute,
  TicketsRoute: TicketsRoute,
  TTenantSlugRoute: TTenantSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
